language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
# command to run tests
script:
  - echo "Running tests"
  - python -m unittest discover
  - if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then coverage run -m unittest discover; fi;

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.8 ]]; then bash <(curl -s https://codecov.io/bash); fi;
